name = "todo_gleam"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
mist = ">= 4.0.4 and < 5.0.0"
wisp = ">= 1.5.1 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.0.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.6 and < 2.0.0"
asset = ">= 1.2.0 and < 2.0.0"

[tailwind]
args = [
  "--input=./input.css",
  "--output=./priv/static/main.css",
  "--minify"
]
